[package]
name = "backpressure"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
eframe = "0.31.0"
egui = "0.31.0"
egui_plot = "0.31.0"
arr_macro = "0.2.1"
tokio = { version = "1.36.0", features = ["full"] }
flume = "0.10.14"